import React from 'react'
import { motion , useScroll, useTransform } from 'framer-motion'
function Scrollbasedanimation() {
    const {scrollYProgress} = useScroll();
    
    const background = useTransform(scrollYProgress,[0,1],["#ff0000","#0000ff"])
  return (
   <>
   <motion.div
   style={{
    position:"sticky",
    transformOrigin:"left" ,
    scaleX:scrollYProgress,
    background, 
    height:"20px",
    width:"100%",
    top:0,
   }}>

   </motion.div>
   
    <div className='px-4'>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis consequatur officiis, natus nisi, nostrum, esse distinctio sit ea ab quos deserunt cum ipsum iste. Debitis sequi, sunt accusamus obcaecati, tempora blanditiis illum aspernatur numquam iusto soluta neque officia veniam eaque dolor labore commodi voluptas harum maxime beatae placeat explicabo nam. Labore officia dicta neque consectetur ab repudiandae magni necessitatibus voluptatem, reprehenderit, minus illo quam repellat itaque. Laboriosam alias blanditiis officia harum rem eligendi, voluptatibus dolorum ipsam, excepturi molestiae sit delectus beatae quis facilis fugiat, totam vero quos. Voluptate culpa hic quasi animi et blanditiis magnam commodi suscipit quibusdam consequuntur eum est, minus corrupti labore quos voluptatum iure reprehenderit! Exercitationem vel sed cum eos, tempore maiores, perspiciatis voluptas in, qui commodi tempora eius totam sequi rem. Porro, eum. Asperiores explicabo ad cumque deserunt, error iure? Facere quia nobis consequuntur fugit possimus amet asperiores ab magnam sed sapiente, vero veniam obcaecati laboriosam aut nam quis enim repellendus dolorum animi soluta itaque atque ullam officia quas? Soluta enim corporis nobis atque, expedita voluptatibus quasi aliquid autem distinctio dolore sint! Ipsum voluptatum quia dicta minus quisquam eveniet ex, nihil culpa, expedita eos doloremque nulla nostrum error dolorem quasi placeat perspiciatis. Harum quae voluptate in!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis consequatur officiis, natus nisi, nostrum, esse distinctio sit ea ab quos deserunt cum ipsum iste. Debitis sequi, sunt accusamus obcaecati, tempora blanditiis illum aspernatur numquam iusto soluta neque officia veniam eaque dolor labore commodi voluptas harum maxime beatae placeat explicabo nam. Labore officia dicta neque consectetur ab repudiandae magni necessitatibus voluptatem, reprehenderit, minus illo quam repellat itaque. Laboriosam alias blanditiis officia harum rem eligendi, voluptatibus dolorum ipsam, excepturi molestiae sit delectus beatae quis facilis fugiat, totam vero quos. Voluptate culpa hic quasi animi et blanditiis magnam commodi suscipit quibusdam consequuntur eum est, minus corrupti labore quos voluptatum iure reprehenderit! Exercitationem vel sed cum eos, tempore maiores, perspiciatis voluptas in, qui commodi tempora eius totam sequi rem. Porro, eum. Asperiores explicabo ad cumque deserunt, error iure? Facere quia nobis consequuntur fugit possimus amet asperiores ab magnam sed sapiente, vero veniam obcaecati laboriosam aut nam quis enim repellendus dolorum animi soluta itaque atque ullam officia quas? Soluta enim corporis nobis atque, expedita voluptatibus quasi aliquid autem distinctio dolore sint! Ipsum voluptatum quia dicta minus quisquam eveniet ex, nihil culpa, expedita eos doloremque nulla nostrum error dolorem quasi placeat perspiciatis. Harum quae voluptate in!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis consequatur officiis, natus nisi, nostrum, esse distinctio sit ea ab quos deserunt cum ipsum iste. Debitis sequi, sunt accusamus obcaecati, tempora blanditiis illum aspernatur numquam iusto soluta neque officia veniam eaque dolor labore commodi voluptas harum maxime beatae placeat explicabo nam. Labore officia dicta neque consectetur ab repudiandae magni necessitatibus voluptatem, reprehenderit, minus illo quam repellat itaque. Laboriosam alias blanditiis officia harum rem eligendi, voluptatibus dolorum ipsam, excepturi molestiae sit delectus beatae quis facilis fugiat, totam vero quos. Voluptate culpa hic quasi animi et blanditiis magnam commodi suscipit quibusdam consequuntur eum est, minus corrupti labore quos voluptatum iure reprehenderit! Exercitationem vel sed cum eos, tempore maiores, perspiciatis voluptas in, qui commodi tempora eius totam sequi rem. Porro, eum. Asperiores explicabo ad cumque deserunt, error iure? Facere quia nobis consequuntur fugit possimus amet asperiores ab magnam sed sapiente, vero veniam obcaecati laboriosam aut nam quis enim repellendus dolorum animi soluta itaque atque ullam officia quas? Soluta enim corporis nobis atque, expedita voluptatibus quasi aliquid autem distinctio dolore sint! Ipsum voluptatum quia dicta minus quisquam eveniet ex, nihil culpa, expedita eos doloremque nulla nostrum error dolorem quasi placeat perspiciatis. Harum quae voluptate in!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis consequatur officiis, natus nisi, nostrum, esse distinctio sit ea ab quos deserunt cum ipsum iste. Debitis sequi, sunt accusamus obcaecati, tempora blanditiis illum aspernatur numquam iusto soluta neque officia veniam eaque dolor labore commodi voluptas harum maxime beatae placeat explicabo nam. Labore officia dicta neque consectetur ab repudiandae magni necessitatibus voluptatem, reprehenderit, minus illo quam repellat itaque. Laboriosam alias blanditiis officia harum rem eligendi, voluptatibus dolorum ipsam, excepturi molestiae sit delectus beatae quis facilis fugiat, totam vero quos. Voluptate culpa hic quasi animi et blanditiis magnam commodi suscipit quibusdam consequuntur eum est, minus corrupti labore quos voluptatum iure reprehenderit! Exercitationem vel sed cum eos, tempore maiores, perspiciatis voluptas in, qui commodi tempora eius totam sequi rem. Porro, eum. Asperiores explicabo ad cumque deserunt, error iure? Facere quia nobis consequuntur fugit possimus amet asperiores ab magnam sed sapiente, vero veniam obcaecati laboriosam aut nam quis enim repellendus dolorum animi soluta itaque atque ullam officia quas? Soluta enim corporis nobis atque, expedita voluptatibus quasi aliquid autem distinctio dolore sint! Ipsum voluptatum quia dicta minus quisquam eveniet ex, nihil culpa, expedita eos doloremque nulla nostrum error dolorem quasi placeat perspiciatis. Harum quae voluptate in!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis consequatur officiis, natus nisi, nostrum, esse distinctio sit ea ab quos deserunt cum ipsum iste. Debitis sequi, sunt accusamus obcaecati, tempora blanditiis illum aspernatur numquam iusto soluta neque officia veniam eaque dolor labore commodi voluptas harum maxime beatae placeat explicabo nam. Labore officia dicta neque consectetur ab repudiandae magni necessitatibus voluptatem, reprehenderit, minus illo quam repellat itaque. Laboriosam alias blanditiis officia harum rem eligendi, voluptatibus dolorum ipsam, excepturi molestiae sit delectus beatae quis facilis fugiat, totam vero quos. Voluptate culpa hic quasi animi et blanditiis magnam commodi suscipit quibusdam consequuntur eum est, minus corrupti labore quos voluptatum iure reprehenderit! Exercitationem vel sed cum eos, tempore maiores, perspiciatis voluptas in, qui commodi tempora eius totam sequi rem. Porro, eum. Asperiores explicabo ad cumque deserunt, error iure? Facere quia nobis consequuntur fugit possimus amet asperiores ab magnam sed sapiente, vero veniam obcaecati laboriosam aut nam quis enim repellendus dolorum animi soluta itaque atque ullam officia quas? Soluta enim corporis nobis atque, expedita voluptatibus quasi aliquid autem distinctio dolore sint! Ipsum voluptatum quia dicta minus quisquam eveniet ex, nihil culpa, expedita eos doloremque nulla nostrum error dolorem quasi placeat perspiciatis. Harum quae voluptate in!</p>

    </div>
   </>
  )
}

export default Scrollbasedanimation